spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 로컬 테스트용 DB
    url: jdbc:mysql://localhost:3306/sammaru?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
  redis:
    host: localhost
    port: 6379

sammaru:
  cookie:
    domain: localhost
    secure: false
  fileDir: src/main/resources/files/