spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 7MB

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  cache:
    type: redis
  redis:
    host: 172.17.0.1
    port: 6379

  output:
    ansi:
      enabled: always

  config:
    import:
      - optional:classpath:/jwt.yml
      - optional:classpath:/mail.yml

---
spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: prod

---
spring:
  profiles:
    active: local
    default: local