devtools:
  livereload:
    enabled: true

spring:

  cache:
    type: redis
  redis:
    host: 172.17.0.1
    port: 6379

  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    #docker
    url: jdbc:mysql://mysql:3306/sammaru?serverTimezone=UTC&characterEncoding=UTF-8
    username: sammaru
    password: sammaru

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false

app:
  jwtRefreshTokenValidTime: 180000
  jwtTokenValidTime: 60000
  jwtSecretKey: SammarufiveSammarufiveSammarufiveSammarufiveSammarufiveSammarufiveSammarufiveSammarufiveSammarufiveSammarufiveSammarufiveSammarufiveSammarufive